version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: chat-backend
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_HOST=http://testingdomain6u1cui.space/
    ports:
      - "80:80"
    container_name: chat-frontend